---
title: "Class 14 DESeq2"
author: "Alanna Koehler"
date: "11/13/2019"
output:
  html_document:
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(DESeq2)
citation("DESeq2")
```

Build the required DESeqDataSet object.
```{r}
dds <- DESeqDataSetFromMatrix(countData=counts,
                              colData=metadata, 
                              design=~dex, 
                              tidy=TRUE)
dds
```

When you run DESeq(), you are doing the following:
```{r}
dds <- DESeq(dds)
```
This function saves the information back into dds.

Get your results
```{r}
res <- results(dds)
res
```

Convert the res object to a data.frame.
```{r}
as.data.frame(res)
```

Make a volcano plot by plotting the log2 fold change vs the inverse of the log of the adjusted p value. 
```{r}
mycols <- rep("gray", nrow(res))
mycols[ abs(res$log2FoldChange) > 2 ]  <- "red" 

inds <- (res$padj < 0.01) & (abs(res$log2FoldChange) > 2 )
mycols[ inds ] <- "blue"

# Volcano plot with custom colors 
plot( res$log2FoldChange,  -log(res$padj), 
 col=mycols, ylab="-Log(P-value)", xlab="Log2(FoldChange)" )

# Cut-off lines
abline(v=c(-2,2), col="gray", lty=2)
abline(h=-log(0.1), col="gray", lty=2)
```

